language: python
python:
  - "2.7"
cache: pip
env:
  - PYTHONPATH=.
services:
  - mongodb
install: "pip install -r requirements_dev.txt"
script: py.test -svvv tests --skip-text-index
after_script:
  - coverage run --include='tests*','anthology*' -m pytest tests --skip-text-index
  - codecov
