language: python
python:
  - "2.7"
cache: pip
services:
  - mongodb
install: "pip install -r requirements_dev.txt"
script: PYTHONPATH=. py.test -svvv tests --skip-text-index
after_script:
  - PYTHONPATH=. coverage run --include='tests*','anthology*' -m pytest tests --skip-text-index
  - PYTHONPATH=. codecov
